{
	"max_concurrent":100,
	"site_concurrent":4,
	"verbose":1,
	"exit_after_done":0,
	"crawler_delay":0.02,
	"page_expires":24,
	"recrawl_sleep":3600,
	"db_dsn":"mysql:host=localhost;dbname=PhpSpider",
	"db_username":"root",
	"db_password":"",
	"useragent":"Mozilla/5.0 (Windows NT 6.1)",
	"site":{
		"360buy.com":{
			"site_id":1,
			"depth":999,
			"list_re":[
				"#^http://www\\.360buy\\.com/products/\\d+-\\d+-\\d+\\.html$#i",
				"#^http://www\\.360buy\\.com/products/\\d+-\\d+-\\d+-0-0-0-0-0-0-0-1-1-\\d+\\.html$#i"
			],
			"info_re":[
				"#^http://www\\.360buy\\.com/product/\\d+\\.html$#i",
				"#^http://(?:book|mvd)\\.360buy\\.com/\\d+\\.html$#i"
			],
			"entry":[
				"http://www.360buy.com/allSort.aspx",
				"http://www.360buy.com/book/booksort.aspx",
				"http://mvd.360buy.com/mvdsort/4051.html",
				"http://mvd.360buy.com/mvdsort/4052.html",
				"http://mvd.360buy.com/mvdsort/4053.html"
			],
			"domain_limit":[
				"www.360buy.com","mvd.360buy.com","book.360buy.com"
			]
		},
		"no5.com.cn":{
			"site_id":2,
			"depth":999,
			"list_re":[
				"#^http://www\\.no5\\.com\\.cn/browse/c\\d+\\.html$#i",
				"#^http://www\\.no5\\.com\\.cn/browse/c\\d+_p\\d+\\.html$#i"
			],
			"info_re":[
				"#^http://www\\.no5\\.com\\.cn/goods/\\d+\\.html$#i"
			],
			"entry":[
				"http://www.no5.com.cn/"
			]
		},
		"redbaby.com.cn":{
			"site_id":3,
			"depth":999,
			"list_re":[
				"#^http://www\\.redbaby\\.com\\.cn/product/p\\d+$#i"
			],
			"info_re":[
				"#^http://www\\.redbaby\\.com\\.cn/[^/]+/\\d+\\.html$#i"
			],
			"entry":[
				"http://www.redbaby.com.cn/product/"
			]
		},
		"coo8.com":{
			"site_id":4,
			"depth":999,
			"list_re":[
				"#^http://www\\.coo8\\.com/products/\\d+-0-0-0-0\\.html$#i",
				"#^http://www\\.coo8\\.com/products/\\d+-0-0-0-\\d+-0-\\d+\\.html$#i"
			],
			"info_re":[
				"#^http://www\\.coo8\\.com/product/\\d+\\.html$#i"
			],
			"entry":[
				"http://www.coo8.com/allcatalog/"
			]
		},
		"xiu.com":{
			"site_id":5,
			"depth":999,
			"info_drop_query":1,
			"list_re":[
				"#^http://list\\.xiu\\.com/\\d+\\.html$#",
				"#^http://list\\.xiu\\.com/\\d+\\.html\\?.*&currentPage=\\d+$#"
			],
			"info_re":[
				"#^http://item\\.xiu\\.com/product/\\d+\\.shtml#i"
			],
			"entry":[
				"http://www.xiu.com/about/classifymap.shtml"
			],
			"domain_limit":[ "list.xiu.com" ]
		},
		"m18.com":{
			"site_id":6,
			"depth":9999,
			"list_re":[
				"#^http://list\\.m18\\.com/[^-]+-[^-]+-12-60-\\d+-00-1-1-N-N-0-0\\.htm$#i"
			],
			"info_re":[
				"#^http://product\\.m18\\.com/p-.+\\.htm$#i"
			],
			"entry":[
				"http://www.m18.com/statichtml/fenlei.html"
			]
		},
		"vjia.com":{
			"site_id":7,
			"depth":999,
			"list_re":[
				"#^http://list\\.vjia\\.com/\\d+\\.html$#i",
				"#^http://list\\.vjia\\.com/\\d+----0-0-6-\\d+--0-0-0---\\.html$#i"
			],
			"info_re":[
				"#^http://item\\.vjia\\.com/\\d+\\.html$#i"
			],
			"entry":[
				"http://www.vjia.com/"
			]
		},
		"womai.com":{
			"site_id":8,
			"depth":999,
			"info_drop_query":1,
			"list_re":[
				"#^http://www\\.womai\\.com/ProductList\\.htm?page=\\d+$#i"
			],
			"info_re":[
				"#^http://www\\.womai\\.com/Product-0-\\d+\\.htm#i"
			],
			"entry":[
				"http://www.womai.com/ProductList.htm?page=1"
			]
		},
		"51buy.com":{
			"site_id":9,
			"depth":999,
			"list_re":[
				"#^http://list\\.51buy\\.com/\\d+--------\\.html$#i",
				"#^http://list\\.51buy\\.com/\\d+-0-6-11-24-0-\\d+--\\.html$#i"
			],
			"info_re":[
				"#^http://item\\.51buy\\.com/item-\\d+\\.html$#i"
			],
			"entry":[
				"http://www.51buy.com/portal.html"
			]
		},
		"lamiu.com":{
			"site_id":10,
			"depth":999,
			"autoredir":1,
			"list_re":[
				"#^http://www\\.lamiu\\.com/search\\.php\\?.*page=\\d+$#i"
			],
			"info_re":[
				"#^http://www\\.lamiu\\.com/goods_\\d+\\.html$#i"
			],
			"entry":[
				"http://www.lamiu.com/search.php?encode=YTowOnt9"
			]
		},
		"letao.com":{
			"site_id":11,
			"depth":999,
			"drop_query":1,
			"list_re":[
				"#^http://www\\.letao\\.com/shoe-[^/]+$#i"
			],
			"info_re":[
				"#^http://www\\.letao\\.com/shoe-[^/]+$#i",
				"#^http://www\\.letao\\.com/[^/]+/shoe-[^/]+$#i"
			],
			"entry":[
				"http://www.letao.com/"
			]
		},
		"vipshop.com":{
			"site_id":12,
			"depth":999,
			"list_re":[
				"#^http://www\\.vipshop\\.com/show-0-\\d+-0\\.html$#i"
			],
			"info_re":[
				"#^http://www\\.vipshop\\.com/detail-\\d+-0-0\\.html$#i"
			],
			"entry":[
				"http://www.vipshop.com/sd.html"
			]
		},
		"mbaobao.com":{
			"site_id":13,
			"depth":999,
			"info_drop_query":1,
			"list_re":[
				"#^http://list\\.mbaobao\\.com/list\\.html\\?ci=#i"
			],
			"info_re":[
				"#^http://item\\.mbaobao\\.com/pshow-\\d+\\.html#i"
			],
			"entry":[
				"http://www.mbaobao.com/"
			]
		},
		"jumei.com":{
			"site_id":14,
			"depth":999,
			"drop_query":1,
			"list_re":[
				"#^http://mall\\.jumei\\.com/products/0-\\d+-0\\.html$#i",
				"#^http://mall\\.jumei\\.com/products/0-\\d+-0-\\d+-0-\\d+-0-11\\.html$#i"
			],
			"info_re":[
				"#^http://mall\\.jumei\\.com/product_\\d+\\.html$#i"
			],
			"entry":[
				"http://mall.jumei.com/"
			]
		},
		"suning.com":{
			"site_id":15,
			"depth":999,
			"list_re":[
				"#^http://www\\.suning\\.com/emall/strd_10052_10051_1_\\d+_\\.html$#i"
			],
			"info_re":[
				"#^http://www\\.suning\\.com/emall/prd_10052_10051_-7_\\d+_\\.html$#i"
			],
			"entry":[
				"http://www.suning.com/"
			]
		},
		"yihaodian.com":{
			"site_id":16,
			"depth":999,
			"list_re":[
				"#^http://www\\.yihaodian\\.com/ctg/s2/[^/]+/b0/a-s1-v0-p\\d+-price-d0-f0-m1-rt0-pid\\d+-k/$#i"
			],
			"info_re":[
				"#^http://www\\.yihaodian\\.com/product/\\d+_\\d+$#i"
			],
			"entry":[
				"http://www.yihaodian.com/2/"
			]
		},
		"newegg.com.cn":{
			"site_id":17,
			"depth":999,
			"list_re":[
				"#^http://www\\.newegg\\.com.cn/SubCategory/\\d+\\.htm$#i",
				"#^http://www\\.newegg\\.com.cn/SubCategory/\\d+-\\d+\\.htm$#i"
			],
			"info_re":[
				"#^http://www\\.newegg\\.com\\.cn/Product/[^/]+\\.htm$#i"
			],
			"entry":[
				"http://www.newegg.com.cn/"
			]
		},
		"yintai.com":{
			"site_id":18,
			"depth":999,
			"list_re":[
				"#^http://www\\.yintai\\.com/product/productlist\\.aspx\\?storetype=1&N=\\d+&sort=0$#i",
				"#^http://www\\.yintai\\.com/product/productlist\\.aspx\\?storetype=1&N=\\d+&sort=0&pageIndex=\\d+$#i"
			],
			"info_re":[
				"#^http://www\\.yintai\\.com/product/productdetail\\.aspx\\?itemcode=#i"
			],
			"entry":[
				"http://www.yintai.com/"
			]
		},
		"dangdang.com":{
			"site_id":19,
			"depth":999,
			"list_re":[
				"#^http://category\\.dangdang\\.com/all/\\?category_(id|path)=[\\.\\d]+$#i",
				"#^http://category\\.dangdang\\.com/all/\\?category_(id|path)=[\\.\\d]+&page_index=#i"
			],
			"info_re":[
				"#^http://product\\.dangdang\\.com/product\\.aspx\\?product_id=\\d+$#i"
			],
			"entry":[
				"http://category.dangdang.com/all/?category_path=01.00.00.00.00.00","http://www.dangdang.com/"
			]
		},
		"vancl.com":{
			"site_id":20,
			"depth":999,
			"list_re":[
				"#^http://s\\.vancl\\.com/search\\?p=\\d+$#i"
			],
			"info_re":[
				"#^http://item\\.vancl\\.com/\\d+\\.html$#i"
			],
			"entry":[
				"http://s.vancl.com/search"
			],
			"domain_limit":[
				"http://s.vancl.com/search?p="
			]
		},
		"amazon.cn":{
			"site_id":21,
			"depth":999,
			"info_re":[
				"#^http://www\\.amazon\\.cn/[^/]+/dp/[^/]+$#i"
			],
			"robots":[
				"http://www.amazon.cn"
			],
			"domain_limit":[
				"www.amazon.cn"
			]
		},
		"moonbasa.com":{
			"site_id":22,
			"depth":999,
			"list_re":[
				"#^http://(?:www|lady)\\.moonbasa\\.com/\\d+-\\d+-\\d+-\\d+\\.html$#i"
			],
			"info_re":[
				"#^http://.+\\.moonbasa\\.com/p-\\d+\\.html$#i"
			],
			"entry":[
				"http://www.moonbasa.com/","http://lady.moonbasa.com/"
			]
		}
	}
}
